config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :partners, only: [:create, :index, :show, :destroy, :new, :edit,:update] do
    collection do
      get :my_service
    end
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :partner
  belongs_to :user
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_one :partner
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
          end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end
  def show
    @booking = Booking.find(params[:id])
    @time = @booking.end_date - @booking.start_date
    @final_price = (@time.to_i * 24) * @booking.partner.price
  end

  def new
    @booking = Booking.new
    @partner = Partner.find(params[:partner_id])
  end

  def create
    @partner = Partner.find(params[:partner_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.partner = @partner
    # @booking.all = @bookings
    if @booking.save

      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    if current_user != nil
      @bookings = Booking.all
      if current_user.partner != nil
        @my_jobs = @bookings.where(partner_id: current_user.partner.id)
      else
        @my_jobs = []
      end
      @my_service = Partner.find_by(user_id: current_user.id)
      @my_bookings = Booking.where(user_id: current_user.id)

    # else
    #   redirect_to root_path
    end
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    @partners = Partner.all
  end

  def show
    @partner = Partner.find(params[:id])
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    @partner.name = current_user.username
    @partner.user_id = current_user.id
    if @partner.save
      redirect_to dashboard_path
   else
    render :message
    end
  end


  def edit
    @partner= Partner.find(params[:id])
  end

  def update
    @partner = Partner.find(params[:id])
    @partner.update(partner_params)
    redirect_to  dashboard_path
  end

  def destroy
    @partner = Partner.find_by(user_id: current_user.id)
    @partner.destroy
    redirect_to root_path, status: :see_other
  end

  def my_service
   @partner = Partner.find_by(user_id: current_user.id)
  end

  private

  def partner_description
    params.require(:partner).permit(:description)
  end

  def partner_params
    params.require(:partner).permit(:description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container p-5">
  <h1>My bookings</h1>
  <%if @bookings.count >= 1%>
    <% @bookings.each do |booking| %>
      <div class="card p-4 mt-3">
        <h1><%= booking.partner.name %></h1>
        <%= cl_image_tag booking.partner.photo.key, height: 300, width: 400, crop: :fill %>
        <p> <strong>From:</strong> <%= booking.start_date %> <strong>To:</strong> <%= booking.end_date %></p>
        <p> <strong>Cost:</strong> <%=((booking.end_date - booking.start_date)* 24) * booking.partner.price %> € </p>

        <div class="btn btn-default cancel-btn d-flex align-items-center justify-content-center">
          <%= link_to "Cancel" , booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <img src="https://cdn.betterttv.net/emote/5baaf017ed3de76aa4212261/3x" alt="sad" width="40px">
        </div>
      </div>
    <% end %>
  <% else %>
      <h2>I'm sorry but no bookings were found...</h2>
      <div class="container d-flex justify-content-center align-items-start">
        <div class="pepe">
          <%= image_tag "pepe_sad" %>
        </div>
      </div>

  <% end %>
</div>

app/views/bookings/new.html.erb
  <div class="container">
  <h1>Confirm and pay</h1>
  </div>

<div class="container card mt-3 p-3">
<h2> You have choosen: <%= @partner.name %></h2>

<%= simple_form_for [@partner, @booking] do |f| %>
  <%= f.input :start_date%>
  <%= f.input :end_date%>
  <%= f.submit %>
<% end %>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5 booked">
  <div class="text-center">
    <h1>Congratulations with your pick! Have a good time ❤️</h1>
  </div>

  <div class="container d-flex align-items-center">
    <div class="container d-flex justify-content-center align-items-start mt-4 mb-4">
      <%= image_tag "fireworks.gif", class:"fireworks"%>
      <div class="card card-tag">
        <h2><%= @booking.partner.name %></h2>
        <p>Check out price: <%= @final_price %>€</p>
      </div>
      <%= image_tag "fireworks.gif", class:"fireworks ms-1"%>
    </div>

    <div class="container d-flex justify-content-center align-items-start">
      <div class="pepe-dance">
        <%= image_tag "pepe-danca.gif" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grabme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar"%>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="text-center mt-4">
  <div class="top-box d-flex justify-content-center">
    <h1>My Profile</h1>
    <%= image_tag "profile-pic.png", class:"pie-chart" %>
  </div>
</div>

<div class="container d-flex flex-column bd-highlight">
  <%if user_signed_in?%>
  <div class="d-flex justify-content-center">
    <%if @my_service != nil%>
      <div class="my-dashboard-card m-3 dashboard-cards p-3">
        <div class="position-of-service-jobs d-flex justify-content-around">
          <div class="my-service">
            <h2>My Service</h2>
            <%= cl_image_tag @my_service.photo.key, height: 300, width: 400, crop: :fill, class:"profile-imgg" %>
            <p class="mt-4"><strong>Description:</strong> <%= @my_service.description %></p>
            <p><strong>Price:</strong> <%=@my_service.price %>€</p>
            <div class="my-service-buttons d-flex">
              <div class="button-1 m-2">
                <%= link_to "Edit", edit_partner_path(@my_service) %>
              </div>
              <div class="button-1 m-2">
                <%= link_to "Delete", partner_path(@my_service), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
          </div>

          <%if current_user.partner != nil%>
            <div class="my-jobs">
              <div class="my-jobs-info">
              <h2>My Clients</h2>
                <% @my_jobs.each do |job| %>
                  <div class="card p-4 m-2 booking-cards">
                    <p> <strong><%=job.user.username %></strong> Booked you!</p>
                    <p> <strong>From:</strong> <%=job.start_date %> <strong>To:</strong> <%= job.end_date %> </p>
                    <p> + <%=(((job.end_date - job.start_date).to_i*24)* job.partner.price )%> € </p>
                  </div>
                <% end %>
            </div>
          </div>
          
          <% elsif current_user.partner == nil%>
            <div class="my-jobs">
              <div class="my-jobs-info">
                <h2>My Clients</h2>
                <p>No clients</p>
            </div>
          <% end %>
        </div>
      </div>

      </div>
    <% else %>
      <div class="btn btn-success">
        <%= link_to "List yourself as a partner!", new_partner_path %>
      </div>
    <% end %>

    <div class="sec-box mt-4">
      <div class="top-box d-flex justify-content-center">
        <h1 class="text-center">My bookings</h1>
        <%= image_tag "booking-confirmation.png", class:"pie-chart" %>
      </div>
      <div class="my-bookings m-3 dashboard-cards-2 ps-3 pe-3 pb-3 pt-2">
        <%if @my_bookings.count >= 1%>
          <% @my_bookings.each do |booking| %>
            <h2><%= booking.partner.name %></h2>
              <div class="mt- d-flex justify-content-between">
                <%= cl_image_tag booking.partner.photo.key, height: 150, width: 150, crop: :fill, class:"booking-picc"%>
                <div class="right-box">
                  <p> <strong>From:</strong> <%= booking.start_date %> <strong>To:</strong> <%= booking.end_date %></p>
                  <p> <strong>Cost:</strong> <%=((booking.end_date - booking.start_date)* 24) * booking.partner.price %> € </p>
                  <div class="cancel-btn d-flex align-items-baseline">
                    <img src="https://cdn.betterttv.net/emote/6018787df1cfbf65dbe15af7/3x" alt="sad" width="40px">
                    <%= link_to "Cancel" , booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  </div>
                </div>
              </div>
              <hr>
          <% end %>
        <% else %>
          <h2>I'm sorry but no bookings were found...</h2>
          <div class="container d-flex justify-content-center align-items-start">
            <div class="pepe">
              <%= image_tag "pepe_sad" %>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
      <h1>User not loged in...</h1>
      <% end %>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="banner d-flex justify-content-center align-items-center">
  <div class="container">
    <% if user_signed_in? %>
    <div class="container-a">
      <div class="row">
        <div class="col-12 text-center" style="background: #ffffff80">
          <h1>Welcome <%= current_user.username %>!</h1>
        </div>
      </div>
    </div>
    <div class="button-container d-flex align-items-center justify-content-center">
      <div class="button-1 me-4 mt-3">
        <%=link_to "Make money! Offer your service.", new_partner_path %>
      </div>
      <div class="button-1 me-2 mt-3 ms2">
        <%=link_to "Check partners available in our network.", partners_path %>
      </div>
    </div>
    <%else%>
      <div class="container-a">
        <div class="row">
          <div class="col-12 text-center" style="background: #ffffff60">
            <span class="text1 mb-0">WELCOME TO GRAB ME</span>
            <span class="text2 text-center">Grab me or never ever</span>
          </div>
          <div class="d-flex justify-content-center">
            <div class="button-1 mt-3">
              <%= link_to "Check partners available in our network.", partners_path %>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/partners/edit.html.erb
<h2>Edit info</h2>

<%= simple_form_for @partner do |f| %>
  <%= f.input :description, as: :text %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price,     as: :float %>
  <%= f.button :submit %>
<% end %>

app/views/partners/index.html.erb
<div class="container d-flex mt-5">
  <div class="row justify-content-center">
    <% if user_signed_in?  %>
      <% @partners.each do |partner| %>
        <div class="col-lg-3 m-3">
          <div class="card-product rounded-4">
          <%if partner.photo.key.present?%>
              <%= cl_image_tag partner.photo.key, height: 300, width: 400, crop: :fill %>
            <% end %>
            <div class="card-product-infos">
              <%if partner.name == current_user.username%>
                <h2><%= partner.name %></h2>
                <p>Price per hour: <%= partner.price %>€</p>
                <p> <strong><%= partner.description %></strong></p>
              <% else %>
                <h2><%= link_to partner.name, partner_path(partner[:id]) %></h2>
                <p>Price per hour: <%= partner.price %>€</p>
                <p><strong><%= partner.description %></strong></p>
                <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <% @partners.each do |partner| %>
        <div class="col-lg-3 m-3">
          <div class="card-product rounded-4">
            <%= cl_image_tag partner.photo.key, height: 300, width: 400, crop: :fill %>
            <div class="card-product-infos">
              <h2><%= link_to partner.name, partner_path(partner[:id]) %></h2>
              <p>Price per hour: <%= partner.price %>€</p>
              <p><strong><%= partner.description %></strong></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partners/my_service.html.erb
<div class="container">
<%if @partner != nil %>
  <h1> My service </h1>

  <div class="card">
    <h2><%= @partner.name %></h2>
    <%= cl_image_tag @partner.photo.key, height: 300, width: 400, crop: :fill %>
    <p><%= @partner.description %></p>
    <p><%=@partner.price%>€</p>
    <%= link_to "Edit", edit_partner_path(@partner) %>
    <%= link_to "Delete", partner_path(@partner), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

  </div>
  <% else %>
    <h1>No Service posted!</h1>
    <div class="button-1">
      <%= link_to "Create one now !", new_partner_path %>
    </div>
    <div class="container d-flex justify-content-center align-items-start">
      <div class="pepe">
        <%= image_tag "pepe_sad" %>
      </div>
    </div>
  <% end %>
</div>

app/views/partners/new.html.erb
<h1>Be a partner!</h1>

<%= simple_form_for(@partner) do |f| %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>

<% end %>

app/views/partners/show.html.erb
<div class="container d-flex flex-column align-items-center mt-4 card-card-box">
  <h2 class="h2-texts mt-1"><%= @partner.name.capitalize %></h2>

  <%= cl_image_tag @partner.photo.key, height: 300, width: 400, crop: :fill, class:"partner-pic"%>

  <%= @partner.description.capitalize %>

  <div class="button-1 mt-1 mb-2"><%= link_to "Grab me",  new_partner_booking_path(params[:id])%></div>
</div>

app/views/shared/_card.html.erb
<div class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p>Product description with <strong>relevant info</strong> only.</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container left"> <!--bot left-->
    <div class="row copyright-text">
        <div class="col-12">
          <p>© 2022 EMA. All Rights Reserved - Le Wagon.</p>
        </div>
    </div>
  </div>
  <div class="container right"> <!--bot right-->
    <div class="row">
      <div class="col-12">
        <div id="social_media">
          <div class="footer-links">
            <a href="#"><i class="fab fa-github"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "hands.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.partner != nil %>
              <%= cl_image_tag current_user.partner.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://i.pinimg.com/736x/97/4f/05/974f05ce910b98c192c09d0b55afd01e.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <p style="text-align:center; border-bottom: 1px solid grey;"><%=current_user.username %></p>
              <a class="dropdown-item" href="/dashboard">My Profile</a>
              <%= link_to "Log out", destroy_user_session_path , class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign up", new_user_registration_path , class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>